### ISSUE TITLE
2.11-beta.1 Appimage refuses to launch on Linux.

### ISSUE THREAD

**Issue by peoii** [WowUp/WowUp.CF#62] opened 2023-09-10 20:20 UTC
**Describe the bug**
As of the latest beta, wowup-cf 2.11-beta.1 refuses tolaunch
**To Reproduce**
1. Attempt to launch the appimage
2. ....
3. Nothing else.

**Expected behavior**
Would expect the app to open.

**Desktop (please complete the following information):**
 - OS: EndeavourOS (Linux)
 - Browser: Firefox
 - Version: 117

**Additional context**
From main.log:

```
[2023-09-10 17:11:22.751] [info]  Main starting
[2023-09-10 17:11:22.755] [info]  Electron: 26.2.0
[2023-09-10 17:11:22.755] [info]  BinaryPath: /tmp/.mount_WowUp-C95XbV/wowup-cf
[2023-09-10 17:11:22.755] [info]  ExecPath /tmp/.mount_WowUp-C95XbV/wowup-cf
[2023-09-10 17:11:22.755] [info]  Args [ '/tmp/.mount_WowUp-C95XbV/wowup-cf' ]
[2023-09-10 17:11:22.756] [info]  Log path: /home/user/.config/WowUpCf/logs
[2023-09-10 17:11:22.756] [info]  ARGV { _: [], serve: false, hidden: false }
[2023-09-10 17:11:22.757] [info]  USER_AGENT WowUp-Client/2.11.0-beta.1 (Linux; 6.4.12-arch1-1; x64; CF;  +https://wowup.io)
[2023-09-10 17:11:22.771] [info]  Hardware acceleration enabled4
```

**Suggestion for future versions**

I attempted to redownload 2.10 to use until this bug could be filed and resolved.  Unfortunately it immediately checks for updates and will not let us choose not to update.   It would be ideal to allow older version to work in the event of these issues.

Cheers.

**Comment by jliddev** [comment] 2023-09-11 03:36
Strange, appears to work fine on ubuntu locally. There is no error in the main or renderer log?

**Comment by SteveEbey73742** [comment] 2023-09-11 21:55
Fedora 38 Also appimage issue, no load, nothing in top or sysinfo to indicate it is even running.  Verified permissions set to execute.

**Comment by jliddev** [comment] 2023-09-11 22:04
I was able to reproduce the issue, looking into it.

**Comment by SteveEbey73742** [comment] 2023-09-12 11:40
You appear to have resolved the issue on my Fedora 38.  Thank you.  Love the application.

**Comment by jliddev** [comment] 2023-09-12 13:33
Closing as fixed

**Closed by jliddev** 2023-09-12 13:33 UTC

**Comment by Proxido** [comment] 2023-09-12 17:40
It starts correctly but the very moment I move a cursor the whole window turns grey. This is coming from arch:

![image](https://github.com/WowUp/WowUp.CF/assets/93446710/7ed94c4a-a294-488e-8f92-9f48cf9c5ada)

19:39:09.402 › webContents render-process-gone
19:39:09.402 › { reason: 'crashed', exitCode: 139 }
19:39:09.402 › Restarting main window
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-RiGs46/resources/app.asar/app/main.js:254:67)
    at BrowserWindow.emit (node:events:525:35)

**Comment by Edu4rdSHL** [comment] 2023-09-12 18:58
I have the same issue as @Proxido

**Comment by Kemmojo** [comment] 2023-09-14 12:26
Same issue here as @Proxido.

- **Arch:** 6.5.3-arch1-1
- Installed **wowup** through [yay](https://github.com/Jguer/yay) -> https://aur.archlinux.org/packages/wowup-cf-bin


Adding to it, if you focus another window ( after moving the mouse inside the wowup window ) you get:
```
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_wowup-bQrwvq/resources/app.asar/app/main.js:257:67)
    at BrowserWindow.emit (node:events:525:35)
```

and if you focus wowup again you get:
```
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_wowup-bQrwvq/resources/app.asar/app/main.js:254:67)
    at BrowserWindow.emit (node:events:525:35)
```

**Comment by tonydero** [comment] 2023-09-18 12:52
Not sure if this helps at all, but this is the journald error I get when it crashes (on Arch Zen kernel 6.5.3, `wowup-cf-bin` version 2.11.0beta2-1) :
```
2023-09-18T06:42:08.645 960651227 systemd-coredump@1-227915-0.service systemd-coredump[227916] CRITICAL Process 226958 (wowup-cf) of user 1000 dumped core.                                                                                                                    │
│                                                                                                                                                                                                                                                                               │
│Stack trace of thread 226958:                                                                                                                                                                                                                                                  │
│#0  0x000055a724be18c3 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x58cf8c3)                                                                                                                                                                                                     │
│#1  0x000055a724be671c n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x58d471c)                                                                                                                                                                                                     │
│#2  0x000055a724be01f4 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x58ce1f4)                                                                                                                                                                                                     │
│#3  0x000055a724afb5d8 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x57e95d8)                                                                                                                                                                                                     │
│#4  0x000055a723eb32d9 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x4ba12d9)                                                                                                                                                                                                     │
│#5  0x000055a72380e50a n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x44fc50a)                                                                                                                                                                                                     │
│#6  0x000055a7237f44e9 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x44e24e9)                                                                                                                                                                                                     │
│#7  0x000055a724a8b55d n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x577955d)                                                                                                                                                                                                     │
│#8  0x000055a724aa7ac4 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x5795ac4)                                                                                                                                                                                                     │
│#9  0x000055a724aa72d9 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x57952d9)                                                                                                                                                                                                     │
│#10 0x000055a724aa8005 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x5796005)                                                                                                                                                                                                     │
│#11 0x000055a724a47a08 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x5735a08)                                                                                                                                                                                                     │
│#12 0x000055a724aa8370 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x5796370)                                                                                                                                                                                                     │
│#13 0x000055a724a6bd31 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x5759d31)                                                                                                                                                                                                     │
│#14 0x000055a72858bb44 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x9279b44)                                                                                                                                                                                                     │
│#15 0x000055a72195e6fb n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x264c6fb)                                                                                                                                                                                                     │
│#16 0x000055a72195fba8 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x264dba8)                                                                                                                                                                                                     │
│#17 0x000055a72195d417 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x264b417)                                                                                                                                                                                                     │
│#18 0x000055a72195d526 n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x264b526)                                                                                                                                                                                                     │
│#19 0x000055a72169121d n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x237f21d)                                                                                                                                                                                                     │
│#20 0x00007fb4f5a27cd0 n/a (libc.so.6 + 0x27cd0)                                                                                                                                                                                                                               │
│#21 0x00007fb4f5a27d8a __libc_start_main (libc.so.6 + 0x27d8a)                                                                                                                                                                                                                 │
│#22 0x000055a72126902a n/a (/tmp/.mount_wowup-LKpnmu/wowup-cf + 0x1f5702a)                                                                                                                                                                                                     │
│ELF object binary architecture: AMD x86-64  
```

**Comment by wyrmss** [comment] 2023-09-25 15:18
17:12:58.950 › window config saved
17:13:05.150 › webContents render-process-gone
17:13:05.150 › { reason: 'crashed', exitCode: 139 }
17:13:05.150 › Restarting main window
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-cMgvnw/resources/app.asar/app/main.js:254:67)
    at BrowserWindow.emit (node:events:525:35)
^C17:13:23.633 › window config saved

**Comment by flamedfury** [comment] 2023-11-19 05:04
I am still experiencing this on Pop!_OS

```bash
OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 6.5.6-76060506-generic
```

**Comment by evensis** [comment] 2024-01-10 18:27
Broken in Linux Mint 21.2 too. Also unable to use older versions that work and don't grey screen (2.10.0 known working) as you are forced to update to the latest version whether you like it or not (assume separate bug).

**Comment by Plyply99** [comment] 2024-02-07 00:52
Issue still happens. 

19:47:15.406 › IPC_APP_UPDATE_STATE app-update-state
19:47:15.406 › { state: 3 }
19:47:15.758 › [GET] https://api.tukui.org/v1/changelog/elvui 200 371ms
19:47:15.874 › Checking for addon updates...
19:47:19.052 › webContents render-process-gone
19:47:19.052 › { reason: 'crashed', exitCode: 139 }
19:47:19.052 › Restarting main window
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-XSgnzB/resources/app.asar/app/main.js:257:67)
    at BrowserWindow.emit (node:events:525:35)

2.10 works fine, but since it is force updating to 2.11 app is now unusable.
Why force the update? To make matters worse it auto deletes the old appimage, not just to the trash but gone from system completely...

Fedora 39 kernel 6.7.3
Happens under Gnome and Hyprland.

**Comment by wc1376c** [comment] 2024-02-07 15:41
> Issue still happens.
> 
> 19:47:15.406 › IPC_APP_UPDATE_STATE app-update-state 19:47:15.406 › { state: 3 } 19:47:15.758 › [GET] https://api.tukui.org/v1/changelog/elvui 200 371ms 19:47:15.874 › Checking for addon updates... 19:47:19.052 › webContents render-process-gone 19:47:19.052 › { reason: 'crashed', exitCode: 139 } 19:47:19.052 › Restarting main window Error sending from webFrameMain: Error: Render frame was disposed before WebFrameMain could be accessed at WebFrameMain.send (node:electron/js2c/browser_init:2:94495) at WebContents.send (node:electron/js2c/browser_init:2:79721) at BrowserWindow. (/tmp/.mount_WowUp-XSgnzB/resources/app.asar/app/main.js:257:67) at BrowserWindow.emit (node:events:525:35)
> 
> 2.10 works fine, but since it is force updating to 2.11 app is now unusable. Why force the update? To make matters worse it auto deletes the old appimage, not just to the trash but gone from system completely...
> 
> Fedora 39 kernel 6.7.3 Happens under Gnome and Hyprland.

How is this closed?  What was the fix?

**Comment by SteveEbey73742** [comment] 2024-02-08 01:27
I hade to remove kernel 6.7.3 in Fedora 39, because it can not compile the nvidia proprietary driver, with dkms. Could try removing kernel 6.7.3 and using previous kernel.

**Comment by Kemmojo** [comment] 2024-02-08 08:34
@Plyply99 
I was able passing by the update popup by pressing `strg + r` ( Reload ).

@SteveEbey73742 
( Wowh, was almost about to update my system. 😳 Thanks for that. ) 
There seams to be a bug within the **Nvidia drivers**, i think it's a function not being gpl compliant, also affecting arch, gentoo, etc. .
Dunno if ppl already implemented quickfixes, but yep, reverting seams to be the option currently.
**Referring to this:** https://forums.developer.nvidia.com/t/linux-6-7-3-545-29-06-550-40-07-error-modpost-gpl-incompatible-module-nvidia-ko-uses-gpl-only-symbol-rcu-read-lock/280908/33?page=2

I run **X** with a **custom dwm build**, Kernel is `6.7.2`.
Also launching the `WowUp-CF-2.11.0` or `WowUp-CF-2.11.1-beta.1` AppImage seam to work fine for me. ( No gray screens, no crashes )

The guys at #63 also seam to have some success. I'll personally stay with the aur package version, which was withheld to `2.10.0` until fixes are stable.

**Comment by wc1376c** [comment] 2024-02-08 15:34
> @Plyply99 and @wc1376c I hade to remove kernel 6.7.3 in Fedora 39, because it can not compile the nvidia proprietary driver, with dkms. Could try removing kernel 6.7.3 and using previous kernel. @Kemmojo are you running Wayland or X and what DE are you running?

Hmm, neither using Nvidia or F39...OK then TY for the response.
